### ISSUE TITLE
Linux build issue (error: ‘memcpy’ was not declared in this scope)

### ISSUE THREAD

**Issue by dgtlmoon** [komrad36/CUDAK2NN#1]
```
g++ -c -I/usr/local/cuda/include/ -Wall -Wextra -Werror -Wshadow -pedantic -Ofast -std=gnu++17 -fomit-frame-pointer -march=native -flto -funroll-all-loops -fpeel-loops -ftracer -ftree-vectorize main.cpp -o main.o
nvcc --use_fast_math -arch=sm_30 -O3 -ccbin cc -std=c++11 -c -I/usr/local/cuda/include/ -Xcompiler "-Wall -Wextra -Werror -Wshadow -Ofast -fomit-frame-pointer -march=native -funroll-all-loops -fpeel-loops -ftracer -ftree-vectorize" CUDAK2NN.cu -o CUDAK2NN.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;

```

**Comment by dgtlmoon** [comment]
Aahh.. it might be applicable to my environment... probably not a bug in your code

**Comment by komrad36** [comment]
No matter, I'm willing to fix it. What's weird about your environment?

**Comment by komrad36** [comment]
NVIDIA cleared up a lot of weird issues like this with CUDA 8, so if you're not on CUDA 8 please try that. It's a good idea anyway for all my stuff. The code is so convoluted because it's generating the very specific PTX that I want, and CUDA 8 is what I build against and is most likely to reliably generate the fastest code as a result.

Note that sm_30 is often faster than sm_52 even if you have a 52 card. Worth trying all the options to get the most speed out!

**Comment by dgtlmoon** [comment]
Yup perfect, installing latest CUDA 8 toolkit fixed everything, thanks again!
